In [13]:
# Importing the datasets


#import scikit-learn and dataset

# Part a and b
from sklearn.datasets import fetch_20newsgroups
categories = [ 'comp.graphics','comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware','rec.autos','rec.motorcycles','rec.sport.baseball','rec.sport.hockey']
twenty_all = fetch_20newsgroups(subset = 'all', categories = categories, shuffle=True, random_state=42)
twenty_train = fetch_20newsgroups(subset = 'train', categories = categories, shuffle=True, random_state=42)
twenty_test = fetch_20newsgroups(subset = 'test', categories = categories, shuffle=True, random_state=42)
length_train = (len(twenty_train.data))
length_test = (len(twenty_test.data))
length_all = len(twenty_all.data)

# Part c

twenty_every = fetch_20newsgroups(subset = 'all',shuffle=True, random_state=42)
length_every = (len(twenty_every.data))

# Multi-class classification
categories_multi = ['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']
twenty_multi_train = fetch_20newsgroups(subset = 'train', categories = categories_multi, shuffle=True, random_state=42)
twenty_multi_test = fetch_20newsgroups(subset = 'test', categories = categories_multi, shuffle=True, random_state=42)
length_multi_train = (len(twenty_multi_train.data))
length_multi_test = (len(twenty_multi_test.data))


In [14]:
# Draw the histogram.


categories_hist = [ 'comp.graphics','comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','rec.autos','rec.motorcycles',
'rec.sport.baseball',
'rec.sport.hockey']

categories_short = [ 'graphics','ms-windows.misc','ibm.pc.hardware','mac.hardware','autos','motorcycles',
'baseball',
'hockey']


twenty_hist = fetch_20newsgroups(subset='all', categories=categories_hist, shuffle=True, random_state=42)


freq0 = 0;
freq1 = 0;
freq2 = 0;
freq3 = 0;
freq4 = 0;
freq5 = 0;
freq6 = 0;
freq7 = 0;
freq8 = 0;

for i in range (0,7882):
    if twenty_hist.target[i] == 0:
        freq0 +=1
    elif twenty_hist.target[i]== 1:
        freq1 +=1
    elif twenty_hist.target[i] == 2:
        freq2 +=1
    elif twenty_hist.target[i]== 3:
        freq3 +=1
    elif twenty_hist.target[i]== 4:
        freq4 +=1
    elif twenty_hist.target[i]== 5:
        freq5 +=1
    elif twenty_hist.target[i]== 6:
        freq6 +=1
    else:
        freq7 +=1        

      

    
import matplotlib.pyplot as plt
import numpy as np
# Learn about API authentication here: https://plot.ly/python/getting-started
# Find your api_key here: https://plot.ly/settings/api

plt.bar([0,1,2,3,4,5,6,7], [freq0,freq1,freq2,freq3,freq4,freq5,freq6,freq7],  color="blue",align = "center")
plt.xticks([0,1,2,3,4,5,6,7], categories_short)
plt.xlabel("Category")
plt.ylabel("Frequency")
plt.show()



In [15]:
# Preprocessing the data


#--------------------------------------------------------------------------------------------------------------------


#Part a and b

import nltk, re, pprint


#Preprocessing the train data

twenty_train_new = list(twenty_train.data) # Modified dataset
porter_train = nltk.LancasterStemmer() # Creating the instance of stemming to be used

for i in range(0,length_train):
  temp_train = twenty_train.data[i].split() # Tokenizing the document
  temp_2_train = [porter_train.stem(t) for t in temp_train] # Replacing the stemming with root words
  twenty_train_new[i] = ' '.join(temp_2_train)


#Preprocessing the test data

twenty_test_new = list(twenty_test.data) # Modified dataset
porter_test = nltk.LancasterStemmer() # Creating the instance of stemming to be used

for k in range(0,length_test):
  temp_test = twenty_test.data[k].split() # Tokenizing the document
  temp_2_test = [porter_test.stem(t) for t in temp_test] # Replacing the stemming with root words
  twenty_test_new[k] = ' '.join(temp_2_test)



#------------------------------------------------------------------------------------------------------------------

#Part c

twenty_every_new = list(twenty_every.data) # Modified dataset
porter_every = nltk.LancasterStemmer() # Creating the instance of stemming to be used

for j in range(0,length_every):
  temp_every = twenty_every.data[i].split() # Tokenizing the document
  temp_2_every = [porter_every.stem(t) for t in temp_every] # Replacing the stemming with root words
  twenty_every_new[i] = ' '.join(temp_2_every)

#-------------------------------------------------------------------------------------------------------------------

# Multiclass classification


#Preprocessing the train data

twenty_multi_train_new = list(twenty_multi_train.data) # Modified dataset
porter_multi_train = nltk.LancasterStemmer() # Creating the instance of stemming to be used

for a in range(0,length_multi_train):
  temp_multi_train = twenty_multi_train.data[a].split() # Tokenizing the document
  temp_2_multi_train = [porter_multi_train.stem(t) for t in temp_multi_train] # Replacing the stemming with root words
  twenty_multi_train_new[a] = ' '.join(temp_2_multi_train)


#Preprocessing the test data

twenty_multi_test_new = list(twenty_multi_test.data) # Modified dataset
porter_multi_test = nltk.LancasterStemmer() # Creating the instance of stemming to be used

for b in range(0,length_multi_test):
  temp_multi_test = twenty_multi_test.data[b].split() # Tokenizing the document
  temp_2_multi_test = [porter_multi_test.stem(t) for t in temp_multi_test] # Replacing the stemming with root words
  twenty_multi_test_new[b] = ' '.join(temp_2_multi_test)

#--------------------------------------------------------------------------------------------------------------------



In [16]:
# Creating the term document matrix with the modified dataset


#-----------------------------------------------------------------------------------------------------------------
# Part a and b
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer
stopWords = text.ENGLISH_STOP_WORDS # Creating the array of stop words

# Creating the term-document matrix for training dataset

count_vect_train = CountVectorizer(stop_words = stopWords) # Creating an object of class CountVectorizer.
t_doc_train = count_vect_train.fit_transform(twenty_train_new) # Creating the term document matrix
print(t_doc_train.shape)

# Creating the term-document matrix for test dataset


t_doc_test = count_vect_train.transform(twenty_test_new) # Creating the term document matrix
print(t_doc_test.shape)

#------------------------------------------------------------------------------------------------------------------


#-----------------------------------------------------------------------------------------------------------------
#Part c

count_vect_every = CountVectorizer(stop_words = stopWords) # Creating an object of class CountVectorizer.
t_doc_every = count_vect_every.fit_transform(twenty_every_new) # Creating the term document matrix
print(t_doc_every.shape)
#------------------------------------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------------------------------------

# Multiclass classification

# Creating the term-document matrix for training dataset

count_vect_multi_train = CountVectorizer(stop_words = stopWords) # Creating an object of class CountVectorizer.
t_doc_multi_train = count_vect_multi_train.fit_transform(twenty_multi_train_new) # Creating the term document matrix
print(t_doc_multi_train.shape)

# Creating the term-document matrix for test dataset

t_doc_multi_test = count_vect_multi_train.transform(twenty_multi_test_new) # Creating the term document matrix
print(t_doc_multi_test.shape)

#------------------------------------------------------------------------------------------------------------------





(4732, 76726)
(3150, 76726)
(18846, 173462)
(2352, 29385)
(1565, 29385)


In [17]:
# Part c. This block of code is under construction and will be completed soon

# Processing to convert the above term-document matrix to term-class matrix

# getting the class info
from scipy.sparse import vstack

class_every = twenty_every.target
#print(twenty_every.target_names[7])
# initializing arrays that holds class indices

class_1 = []
class_2 = []
class_3 = []
class_4 = []
class_5 = []
class_6 = []
class_7 = []
class_8 = []
class_9 = []
class_10 = []
class_11 = []
class_12 = []
class_13 = []
class_14 = []
class_15 = []
class_16 = []
class_17 = []
class_18 = []
class_19 = []
class_20 = []


for m in range(0,length_every):
    if class_every[m] == 0:
        class_1.append(m)
    
    elif class_every[m] == 1:
        class_2.append(m)
    
    elif class_every[m] == 2:
        class_3.append(m)
    
    elif class_every[m] == 3:
        class_4.append(m)
    
    elif class_every[m] == 4:
        class_5.append(m)
    
    elif class_every[m] == 5:
        class_6.append(m)
    
    elif class_every[m] == 6:
        class_7.append(m)
    
    elif class_every[m] == 7:
        class_8.append(m)
    
    elif class_every[m] == 8:
        class_9.append(m)
    
    elif class_every[m] == 9:
        class_10.append(m)
    
    elif class_every[m] == 10:
        class_11.append(m)
    
    elif class_every[m] == 11:
        class_12.append(m)
    
    elif class_every[m] == 12:
        class_13.append(m)
    
    elif class_every[m] == 13:
        class_14.append(m)
    
    elif class_every[m] == 14:
        class_15.append(m)
    
    elif class_every[m] == 15:
        class_16.append(m)
    
    elif class_every[m] == 16:
        class_17.append(m)
    
    elif class_every[m] == 17:
        class_18.append(m)
    
    elif class_every[m] == 19:
        class_19.append(m)
    
    else:
        class_20.append(m)
        
#class_list = [class_1,class_2,class_3,class_4,class_5,class_6,class_7,class_8,class_9,class_10,class_11,class_12,class_13,class_14,
      #       class_15,class_16,class_17,class_18,class_19]
        
# Create the Term-Class matrix:

sum_1= t_doc_every[class_1[0],:];
for j in range(1,len(class_1)):
    sum_1 = sum_1 + t_doc_every[class_1[j],:]

sum_2= t_doc_every[class_2[0],:];
for j in range(1,len(class_2)):
    sum_2 = sum_2 + t_doc_every[class_2[j],:]
    
sum_3= t_doc_every[class_3[0],:];
for j in range(1,len(class_3)):
    sum_3 = sum_3 + t_doc_every[class_3[j],:]

sum_4= t_doc_every[class_4[0],:];
for j in range(1,len(class_4)):
    sum_4 = sum_4 + t_doc_every[class_4[j],:]
    
sum_5= t_doc_every[class_5[0],:];
for j in range(1,len(class_5)):
    sum_5 = sum_5 + t_doc_every[class_5[j],:]
    
sum_6= t_doc_every[class_6[0],:];
for j in range(1,len(class_6)):
    sum_6 = sum_6 + t_doc_every[class_6[j],:]
    
sum_7= t_doc_every[class_7[0],:];
for j in range(1,len(class_7)):
    sum_7 = sum_7 + t_doc_every[class_7[j],:]

sum_8= t_doc_every[class_8[0],:];
for j in range(1,len(class_8)):
    sum_8 = sum_8 + t_doc_every[class_8[j],:]

sum_9= t_doc_every[class_9[0],:];
for j in range(1,len(class_9)):
    sum_9 = sum_9 + t_doc_every[class_9[j],:]

sum_10= t_doc_every[class_10[0],:];
for j in range(1,len(class_10)):
    sum_10 = sum_10 + t_doc_every[class_10[j],:]

sum_11= t_doc_every[class_11[0],:];
for j in range(1,len(class_11)):
    sum_11 = sum_11 + t_doc_every[class_11[j],:]

sum_12= t_doc_every[class_12[0],:];
for j in range(1,len(class_12)):
    sum_12 = sum_12 + t_doc_every[class_12[j],:]
    
sum_13= t_doc_every[class_13[0],:];
for j in range(1,len(class_13)):
    sum_13 = sum_13 + t_doc_every[class_13[j],:]

sum_14= t_doc_every[class_14[0],:];
for j in range(1,len(class_14)):
    sum_14 = sum_14 + t_doc_every[class_14[j],:]
    
sum_15= t_doc_every[class_15[0],:];
for j in range(1,len(class_15)):
    sum_15 = sum_15 + t_doc_every[class_15[j],:]
    
sum_16= t_doc_every[class_16[0],:];
for j in range(1,len(class_16)):
    sum_16 = sum_16 + t_doc_every[class_16[j],:]
    
sum_17= t_doc_every[class_17[0],:];
for j in range(1,len(class_17)):
    sum_17 = sum_17 + t_doc_every[class_17[j],:]

sum_18= t_doc_every[class_18[0],:];
for j in range(1,len(class_18)):
    sum_18 = sum_18 + t_doc_every[class_18[j],:]

sum_19= t_doc_every[class_19[0],:];
for j in range(1,len(class_19)):
    sum_19 = sum_19 + t_doc_every[class_19[j],:]

sum_20= t_doc_every[class_20[0],:];
for j in range(1,len(class_20)):
    sum_20 = sum_20 + t_doc_every[class_20[j],:]

    
t_class_every = vstack((sum_1,sum_2,sum_3,sum_4,sum_5,sum_6,sum_7,sum_8,sum_9,sum_10,sum_11,sum_12,sum_13,sum_14,sum_15,
                            sum_16,sum_17,sum_18,sum_19,sum_20));
    


In [18]:
#part c continued

#create TF-ICF
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

tficf_transformer = TfidfTransformer() # Creating an object of class TfidfTransformer


tficf = tficf_transformer.fit_transform(t_class_every) # Creating the tfidf matrix

    
sorted_pc_hardware = np.argsort(tficf[3,:].toarray()) 
sorted_mac_hardware = np.argsort(tficf[4,:].toarray())
sorted_forsale= np.argsort(tficf[6,:].toarray())
sorted_rel_christian = np.argsort(tficf[15,:].toarray())

words = np.asarray(count_vect_every.get_feature_names())

#print(words[170325])
print("Common Words for PC Hardware (in reverse order):")
for i in range(len(words)-10,len(words)):
    print(words[sorted_pc_hardware[0,i]])

print('\n')   
print("Common Words for MAC Hardware (in reverse order):")
    
for i in range(len(words)-10,len(words)):
    print(words[sorted_mac_hardware[0,i]])

print('\n')   
print("Common Words for 'For Sale' (in reverse order):")    
for i in range(len(words)-10,len(words)):
    print(words[sorted_forsale[0,i]])
    
    
print('\n')   
print("Common Words for Religion.Christian (in reverse order):")
for i in range(len(words)-10,len(words)):
    print(words[sorted_rel_christian[0,i]])
    
    

#3,4,6,15

Common Words for PC Hardware (in reverse order):
card
controller
organization
subject
lines
drive
ide
com
edu
scsi


Common Words for MAC Hardware (in reverse order):
university
scsi
centris
quadra
apple
organization
mac
subject
lines
edu


Common Words for 'For Sale' (in reverse order):
10
new
com
university
organization
sale
lines
subject
00
edu


Common Words for Religion.Christian (in reverse order):
athos
lines
christ
people
church
subject
jesus
christians
edu
god


In [19]:
# Creating the tfidf matrix with the modified dataset

from sklearn.feature_extraction.text import TfidfTransformer


#------------------------------------------------------------------------------------------------------------------
# Binary classification


# Creating the tf-idf for training dataset

tfidf_transformer_train = TfidfTransformer() # Creating an object of class TfidfTransformer
tfidf_train = tfidf_transformer_train.fit_transform(t_doc_train) # Creating the tfidf matrix
print(tfidf_train.shape)

# Creating the tf-idf for test dataset


tfidf_test = tfidf_transformer_train.transform(t_doc_test) # Creating the tfidf matrix
print(tfidf_test.shape)

#-------------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------------
#Multiclass classification

# Creating the tf-idf for training dataset

tfidf_transformer_multi_train = TfidfTransformer() # Creating an object of class TfidfTransformer
tfidf_multi_train = tfidf_transformer_multi_train.fit_transform(t_doc_multi_train) # Creating the tfidf matrix
print(tfidf_multi_train.shape)


# Creating the tf-idf for test dataset

tfidf_multi_test = tfidf_transformer_multi_train.transform(t_doc_multi_test) # Creating the tfidf matrix
print(tfidf_multi_test.shape)


#--------------------------------------------------------------------------------------------------------------------


(4732, 76726)
(3150, 76726)
(2352, 29385)
(1565, 29385)


In [20]:

# Applying LSI to training and test tf-idf matrix


from sklearn.decomposition import TruncatedSVD

#------------------------------------------------------------------------------------------------------------------
# Binary classification


# Applying to the training set

lsa_transformer_train = TruncatedSVD(50, random_state = 42 )
lsa_train = lsa_transformer_train.fit_transform(tfidf_train)
print(lsa_train.shape)

# Applying to the test set


lsa_test = lsa_transformer_train.transform(tfidf_test)
print(lsa_test.shape)

#-------------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------------
# Multiclass classification

# Applying to the training set

lsa_transformer_multi_train = TruncatedSVD(50, random_state = 42 )
lsa_multi_train = lsa_transformer_multi_train.fit_transform(tfidf_multi_train)
print(lsa_multi_train.shape)


# Applying to the test set


lsa_multi_test = lsa_transformer_multi_train.transform(tfidf_multi_test)
print(lsa_multi_test.shape)

#--------------------------------------------------------------------------------------------------------------------



# Note: This lsa_train matrix will be used in training the classifiers and lsa_test matrix will be used to test the performance of the classifiers.


(4732, 50)
(3150, 50)
(2352, 50)
(1565, 50)


In [22]:
# Processing for classification

# Creating the array of class labels for binary classification

# Training dataset

class_train = []

for a in range(0,length_train):
    if twenty_train.target[a] < 4:
        class_train.append(0)
    
    else:
        class_train.append(1)


#print(class_train[0])

# Test dataset

class_test = []

for b in range(0,length_test):
    if twenty_test.target[b] < 4:
        class_test.append(0)
    
    else:
        class_test.append(1)

#print(len(class_test))

In [23]:
# Binary Classification

# Importing the required classifiers

from sklearn.svm import LinearSVC
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc

from sklearn import metrics
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np

#---------------------------------------------------------------------------------------------------------
# Linear SVM classifier (Hard Margin)

clf_lin_svm = LinearSVC(random_state=42).fit(lsa_train,class_train)
predicted_lin_svm = clf_lin_svm.predict(lsa_test)
lin_svm_acc = accuracy_score(class_test, predicted_lin_svm)
print('Linear SVM classifier results')
print()
print('Accuracy score')
print(lin_svm_acc)
print()
print('Classification report')
print(metrics.classification_report(class_test, predicted_lin_svm,
    target_names=['Computer Technology', 'Recreational Activity']))

print()
lin_svm_metric = metrics.confusion_matrix(class_test, predicted_lin_svm)
print('Confusion matrix')
print(lin_svm_metric)
print()
print('--------------------------------------------------------------------------------------')

# ROC plotting for Linear SVM classifier (Hard Margin)

fpr_svm = []
tpr_svm = []
roc_auc_svm = []
scores_svm = clf_lin_svm.decision_function(lsa_test)

fpr_svm, tpr_svm, thresholds_svm = metrics.roc_curve(class_test,scores_svm)
roc_auc_svm = auc(fpr_svm,tpr_svm)

plt.figure()
plt.plot(fpr_svm, tpr_svm, label='ROC curve (area = %0.4f)' % roc_auc_svm)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating for Linear SVM')
plt.legend(loc="lower right")
plt.show()

#------------------------------------------------------------------------------------------------------------------



# Linear SVM classifier (Soft Margin)

clf_svm_soft = GridSearchCV(LinearSVC(), param_grid={'C': [0.001,0.01,0.1,1,10,100,1000]},cv = 5, scoring = 'accuracy')
clf_svm_soft.fit(lsa_train,class_train)
print('Soft margin SVM classifier results for the optimal C with 5-fold CV')
print()
print('Optimal C')
print()
print(clf_svm_soft.best_params_)
print()
predicted_svm_soft = clf_svm_soft.predict(lsa_test)
svm_soft_acc = accuracy_score(class_test, predicted_svm_soft)
print('Accuracy score')
print(svm_soft_acc)
print()
print('Classification report')
print(metrics.classification_report(class_test, predicted_svm_soft,
    target_names=['Computer Technology', 'Recreational Activity']))

print()
print('Confusion matrix')
svm_soft_metric = metrics.confusion_matrix(class_test, predicted_svm_soft)
print(svm_soft_metric)
print()
print('---------------------------------------------------------------------------------------------------')




#---------------------------------------------------------------------------------------------------------------------



#--------------------------------------------------------------------------------------------------------------------

# Gaussian NB classifier

clf_gauss_nb = GaussianNB().fit(lsa_train,class_train)
predicted_gauss_nb = clf_gauss_nb.predict(lsa_test)
gaussian_nb_acc = accuracy_score(class_test, predicted_gauss_nb)
print('Gaussian NB classifier results')
print()
print('Accuracy score')
print(gaussian_nb_acc)
print()
print('Classification report')
print(metrics.classification_report(class_test, predicted_gauss_nb,
    target_names=['Computer Technology', 'Recreational Activity']))
print()
gaussian_nb_metric = metrics.confusion_matrix(class_test, predicted_gauss_nb)
print('Confusion matrix')
print(gaussian_nb_metric)
print()
print('--------------------------------------------------------------------------------------------------------')







# ROC plotting for gaussian NB

fpr_nb = []
tpr_nb = []
roc_auc_nb = []
scores_nb = clf_gauss_nb.predict_proba(lsa_test)
fpr_nb, tpr_nb, thresholds_nb = metrics.roc_curve(class_test,scores_nb[:,1])
roc_auc_nb = auc(fpr_nb,tpr_nb)

plt.figure()
plt.plot(fpr_nb, tpr_nb, label='ROC curve (area = %0.4f)' % roc_auc_nb)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic for Gaussian Naive Bayes')
plt.legend(loc="lower right")
plt.show()


#--------------------------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------------------------


# Logistic regression classifier

clf_logistic = LogisticRegression().fit(lsa_train,class_train)
predicted_logistic = clf_logistic.predict(lsa_test)
print('Logistic regression classifier results')
print()
logistic_acc = accuracy_score(class_test, predicted_logistic)
print('Accuracy score')
print(logistic_acc)
print()
print('Classification report')
print(metrics.classification_report(class_test, predicted_logistic,
    target_names=['Computer Technology', 'Recreational Activity']))
print()
logistic_metric = metrics.confusion_matrix(class_test, predicted_logistic)
print('Confusion matrix')
print(logistic_metric)
print()
print('------------------------------------------------------------------------------------------------------')




# ROC plotting for logistic

fpr_logistic = []
tpr_logistic = []
roc_auc_logistic = []
scores_logistic = clf_logistic.decision_function(lsa_test)

fpr_logistic, tpr_logistic, thresholds_logistic = metrics.roc_curve(class_test,scores_logistic)
roc_auc_logistic = auc(fpr_logistic,tpr_logistic)

plt.figure()
plt.plot(fpr_logistic, tpr_logistic, label='ROC curve (area = %0.4f)' % roc_auc_logistic)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating for Logistic')
plt.legend(loc="lower right")
plt.show()

#--------------------------------------------------------------------------------------------------------------------

Linear SVM classifier results

Accuracy score
0.966984126984

Classification report
                       precision    recall  f1-score   support

  Computer Technology       0.98      0.95      0.97      1560
Recreational Activity       0.96      0.98      0.97      1590

          avg / total       0.97      0.97      0.97      3150


Confusion matrix
[[1488   72]
 [  32 1558]]

--------------------------------------------------------------------------------------
Soft margin SVM classifier results for the optimal C with 5-fold CV

Optimal C

{'C': 10}

Accuracy score
0.967936507937

Classification report
                       precision    recall  f1-score   support

  Computer Technology       0.98      0.96      0.97      1560
Recreational Activity       0.96      0.98      0.97      1590

          avg / total       0.97      0.97      0.97      3150


Confusion matrix
[[1496   64]
 [  37 1553]]

-----------------------------------------------------------------------------------

In [24]:
# Plotting the ROC curves on the same plot for comparison

plt.plot(fpr_svm, tpr_svm,'r', label='ROC curve (area = %0.4f)' % roc_auc_svm)
plt.plot(fpr_nb, tpr_nb,'b', label='ROC curve (area = %0.4f)' % roc_auc_nb)
plt.plot(fpr_logistic, tpr_logistic,'g', label='ROC curve (area = %0.4f)' % roc_auc_logistic)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Comparison')
plt.legend(loc="lower right")
plt.show()

In [25]:
# Multiclass classification

from sklearn import svm

#-------------------------------------------------------------------------------------------------------------------
# SVM OVO 

clf_svm_ovo = svm.SVC(decision_function_shape='ovo',kernel = 'linear',random_state=42)
clf_svm_ovo.fit(lsa_multi_train,twenty_multi_train.target)
predicted_svm_ovo = clf_svm_ovo.predict(lsa_multi_test)
svm_ovo_acc = accuracy_score(twenty_multi_test.target, predicted_svm_ovo)
print('SVM OVO classifier results')
print()
print('Accuracy score')
print(svm_ovo_acc)
print()
print('Classification report')
print(metrics.classification_report(twenty_multi_test.target, predicted_svm_ovo,
    target_names=['comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware','misc.forsale','soc.religion.christian']))

print()
svm_ovo_metric = metrics.confusion_matrix(twenty_multi_test.target, predicted_svm_ovo)
print('Confusion matrix')
print(svm_ovo_metric)
print()
print('--------------------------------------------------------------------------------------')

#-------------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------------
# SVM OVR

clf_svm_ovr = svm.LinearSVC(random_state = 42)
clf_svm_ovr.fit(lsa_multi_train,twenty_multi_train.target)
predicted_svm_ovr = clf_svm_ovr.predict(lsa_multi_test)
svm_ovr_acc = accuracy_score(twenty_multi_test.target, predicted_svm_ovr)
print('SVM OVR classifier results')
print()
print('Accuracy score')
print(svm_ovr_acc)
print()
print('Classification report')
print(metrics.classification_report(twenty_multi_test.target, predicted_svm_ovr,
    target_names=['comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware','misc.forsale','soc.religion.christian']))

print()
svm_ovr_metric = metrics.confusion_matrix(twenty_multi_test.target, predicted_svm_ovr)
print('Confusion matrix')
print(svm_ovr_metric)
print()
print('--------------------------------------------------------------------------------------')

#--------------------------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------------------------
# Gaussian NB 


clf_gauss_nb_multi = GaussianNB().fit(lsa_multi_train,twenty_multi_train.target)
predicted_gauss_nb_multi = clf_gauss_nb_multi.predict(lsa_multi_test)
gaussian_nb_multi_acc = accuracy_score(twenty_multi_test.target, predicted_gauss_nb_multi)
print('Gaussian NB classifier results')
print()
print('Accuracy score')
print(gaussian_nb_multi_acc)
print()
print('Classification report')
print(metrics.classification_report(twenty_multi_test.target, predicted_gauss_nb_multi,
    target_names=['comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware','misc.forsale','soc.religion.christian']))
print()
gaussian_nb_multi_metric = metrics.confusion_matrix(twenty_multi_test.target, predicted_gauss_nb_multi)
print('Confusion matrix')
print(gaussian_nb_multi_metric)
print()
print('--------------------------------------------------------------------------------------------------------')

#--------------------------------------------------------------------------------------------------------------------









SVM OVO classifier results

Accuracy score
0.85750798722

Classification report
                          precision    recall  f1-score   support

comp.sys.ibm.pc.hardware       0.77      0.81      0.79       392
   comp.sys.mac.hardware       0.86      0.78      0.82       385
            misc.forsale       0.82      0.90      0.86       390
  soc.religion.christian       0.99      0.94      0.97       398

             avg / total       0.86      0.86      0.86      1565


Confusion matrix
[[317  38  37   0]
 [ 55 300  29   1]
 [ 28  11 350   1]
 [ 11   1  11 375]]

--------------------------------------------------------------------------------------
SVM OVR classifier results

Accuracy score
0.875399361022

Classification report
                          precision    recall  f1-score   support

comp.sys.ibm.pc.hardware       0.83      0.79      0.81       392
   comp.sys.mac.hardware       0.84      0.82      0.83       385
            misc.forsale       0.84      0.92      0.88   